
module: default
runtime: python27
vm: true

api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: producer.app

libraries:
- name: webapp2
  version: latest
#- name: httplib2
#  version: latest
